### ISSUE TITLE
preventDefault() for Enter key?

### ISSUE THREAD

**Issue by adrianbj** [rolandtoth/FilterBox#1]
For my implementation in Tracy at least, it looks a little cleaner if there is a: `e.preventDefault();` after this line: https://github.com/rolandtoth/FilterBox/blob/caabd07e6e28afc3966a6e06628e24315e95161c/filterbox/filterbox.js#L821

Do you think this would be ok for all uses?

**Comment by rolandtoth** [comment]
I pass the event object to allow the developer decide whether to use preventDefault(). I haven't had a need for that so far, but this way it doesn't potentially block other events on the input, if any.

**Comment by adrianbj** [comment]
Thanks - I made the change in the callback instead!
